package com.gitee.pro.mapper;

import com.gitee.pro.entity.Admin;
import com.gitee.pro.entity.AdminExample;

import java.util.List;

import org.apache.ibatis.annotations.Param;

public interface AdminMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_admin
     *
     * @mbg.generated Mon Dec 05 15:06:10 CST 2022
     */
    long countByExample(AdminExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_admin
     *
     * @mbg.generated Mon Dec 05 15:06:10 CST 2022
     */
    int deleteByExample(AdminExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_admin
     *
     * @mbg.generated Mon Dec 05 15:06:10 CST 2022
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_admin
     *
     * @mbg.generated Mon Dec 05 15:06:10 CST 2022
     */
    int insert(Admin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_admin
     *
     * @mbg.generated Mon Dec 05 15:06:10 CST 2022
     */
    int insertSelective(Admin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_admin
     *
     * @mbg.generated Mon Dec 05 15:06:10 CST 2022
     */
    List<Admin> selectByExample(AdminExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_admin
     *
     * @mbg.generated Mon Dec 05 15:06:10 CST 2022
     */
    Admin selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_admin
     *
     * @mbg.generated Mon Dec 05 15:06:10 CST 2022
     */
    int updateByExampleSelective(@Param("record") Admin record, @Param("example") AdminExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_admin
     *
     * @mbg.generated Mon Dec 05 15:06:10 CST 2022
     */
    int updateByExample(@Param("record") Admin record, @Param("example") AdminExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_admin
     *
     * @mbg.generated Mon Dec 05 15:06:10 CST 2022
     */
    int updateByPrimaryKeySelective(Admin record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_admin
     *
     * @mbg.generated Mon Dec 05 15:06:10 CST 2022
     */
    int updateByPrimaryKey(Admin record);

    /**
     * 自定义
     * 用于关键字查询的接口
     *
     * @param keyword 查询的关键字
     * @return 含有关键字的 admin
     */
    List<Admin> selectAdminByKeyword(String keyword);

    /**
     * 自定义
     * 删除旧的关联关系
     *
     * @param adminId 用户 id
     */
    void deleteOldRelationship(Integer adminId);

    /**
     * 自定义
     * 添加新的关联关系
     *
     * @param adminId    用户 id
     * @param roleIdList 要关联的角色 id 集合
     */
    void insertNewRelationship(@Param("adminId") Integer adminId, @Param("roleIdList") List<Integer> roleIdList);
}