package com.gitee.pro.entity;

import java.util.ArrayList;
import java.util.List;

public class Menu {
    /**
     * 主键
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_menu.id
     *
     * @mbg.generated Fri Dec 23 19:00:37 CST 2022
     */
    private Integer id;

    /**
     * 父节点 id
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_menu.pid
     *
     * @mbg.generated Fri Dec 23 19:00:37 CST 2022
     */
    private Integer pid;

    /**
     * 节点名称
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_menu.name
     *
     * @mbg.generated Fri Dec 23 19:00:37 CST 2022
     */
    private String name;

    /**
     * 节点附带的 url 地址
     * 点击菜单项跳转的地址
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_menu.url
     *
     * @mbg.generated Fri Dec 23 19:00:37 CST 2022
     */
    private String url;

    /**
     * 节点图标样式
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column t_menu.icon
     *
     * @mbg.generated Fri Dec 23 19:00:37 CST 2022
     */
    private String icon;

    /**
     * 下属子节点集合
     * 初始化是为了避免空指针异常
     */
    private List<Menu> children = new ArrayList<>();

    /**
     * 控制节点是否默认为打开
     * 设置为 true 表示默认打开
     */
    private Boolean open = true;

    public Menu() {
    }

    public Menu(Integer id, Integer pid, String name, String url, String icon, List<Menu> children, Boolean open) {
        this.id = id;
        this.pid = pid;
        this.name = name;
        this.url = url;
        this.icon = icon;
        this.children = children;
        this.open = open;
    }

    @Override
    public String toString() {
        return "Menu{" +
                "id=" + id +
                ", pid=" + pid +
                ", name='" + name + '\'' +
                ", url='" + url + '\'' +
                ", icon='" + icon + '\'' +
                ", children=" + children +
                ", open=" + open +
                '}';
    }

    public List<Menu> getChildren() {
        return children;
    }

    public void setChildren(List<Menu> children) {
        this.children = children;
    }

    public Boolean getOpen() {
        return open;
    }

    public void setOpen(Boolean open) {
        this.open = open;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_menu.id
     *
     * @return the value of t_menu.id
     * @mbg.generated Fri Dec 23 19:00:37 CST 2022
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_menu.id
     *
     * @param id the value for t_menu.id
     * @mbg.generated Fri Dec 23 19:00:37 CST 2022
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_menu.pid
     *
     * @return the value of t_menu.pid
     * @mbg.generated Fri Dec 23 19:00:37 CST 2022
     */
    public Integer getPid() {
        return pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_menu.pid
     *
     * @param pid the value for t_menu.pid
     * @mbg.generated Fri Dec 23 19:00:37 CST 2022
     */
    public void setPid(Integer pid) {
        this.pid = pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_menu.name
     *
     * @return the value of t_menu.name
     * @mbg.generated Fri Dec 23 19:00:37 CST 2022
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_menu.name
     *
     * @param name the value for t_menu.name
     * @mbg.generated Fri Dec 23 19:00:37 CST 2022
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_menu.url
     *
     * @return the value of t_menu.url
     * @mbg.generated Fri Dec 23 19:00:37 CST 2022
     */
    public String getUrl() {
        return url;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_menu.url
     *
     * @param url the value for t_menu.url
     * @mbg.generated Fri Dec 23 19:00:37 CST 2022
     */
    public void setUrl(String url) {
        this.url = url == null ? null : url.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column t_menu.icon
     *
     * @return the value of t_menu.icon
     * @mbg.generated Fri Dec 23 19:00:37 CST 2022
     */
    public String getIcon() {
        return icon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column t_menu.icon
     *
     * @param icon the value for t_menu.icon
     * @mbg.generated Fri Dec 23 19:00:37 CST 2022
     */
    public void setIcon(String icon) {
        this.icon = icon == null ? null : icon.trim();
    }
}